# -*- coding: utf-8 -*-
"""nnUNet_smoke_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXmlA5GOACFZTgoJDiT5MAa_orJEUnfg
"""

import importlib.util
import subprocess
import sys

if importlib.util.find_spec("nnunetv2") is None:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "nnunetv2"])
else:
    print("nnUNet is already installed.")

import os

os.environ["nnUNet_raw"] = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_raw"
os.environ["nnUNet_preprocessed"] = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_preprocessed"
os.environ["nnUNet_results"] = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_results"

!nnUNetv2_train 501 3d_fullres 0 -device cuda