# -*- coding: utf-8 -*-
"""nnUNet_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rw0AbZoA2UESB0YvSyUdtWT2Bc41mFSs
"""

import importlib.util
import subprocess
import sys

if importlib.util.find_spec("nnunetv2") is None:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "nnunetv2"])
else:
    print("nnUNet is already installed.")

import os
import glob

data_root = "/content/drive/MyDrive/HECKTOR_2026/HECKTOR 2026 Training Data"

patient_dirs = sorted([
    p for p in glob.glob(os.path.join(data_root, "*"))
    if os.path.isdir(p)
])

# Take first 5 patients
patient_dirs = patient_dirs[:5]

for p in patient_dirs:
    print(os.path.basename(p))

for patient_dir in patient_dirs:
    patient_id = os.path.basename(patient_dir)

    gt_path = os.path.join(patient_dir, f"{patient_id}.nii.gz")
    ct_path = os.path.join(patient_dir, f"{patient_id}__CT.nii.gz")
    pet_path = os.path.join(patient_dir, f"{patient_id}__PT.nii.gz")

    print(patient_id)
    print("  GT :", os.path.exists(gt_path), gt_path)
    print("  CT :", os.path.exists(ct_path), ct_path)
    print("  PET:", os.path.exists(pet_path), pet_path)

import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt
from nibabel.processing import resample_from_to
from matplotlib.colors import ListedColormap

# Select patient
patient_dir = patient_dirs[0]  # Change patient index here
patient_id = os.path.basename(patient_dir)

ct = nib.load(os.path.join(patient_dir, f"{patient_id}__CT.nii.gz"))
pet = nib.load(os.path.join(patient_dir, f"{patient_id}__PT.nii.gz"))
gt = nib.as_closest_canonical(
    nib.load(os.path.join(patient_dir, f"{patient_id}.nii.gz"))
)

# Find the axial slice containing the most labeled tumor voxels
labels = np.asarray(gt.dataobj)
tumor_area = (labels > 0).sum(axis=(0, 1))  # Use labels == 1 for primary tumor only

if tumor_area.max() == 0:
    raise ValueError("No tumor labels found for this patient.")

z = int(tumor_area.argmax())
gt_slice = gt.slicer[:, :, z:z + 1]

# Sample CT and PET onto the selected GT slice's physical grid
ct_slice = resample_from_to(ct, gt_slice, order=1).get_fdata()[:, :, 0]
pet_slice = resample_from_to(pet, gt_slice, order=1).get_fdata()[:, :, 0]

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
axes[0].imshow(ct_slice.T, cmap="gray", origin="lower", vmin=-160, vmax=240)
axes[1].imshow(pet_slice.T, cmap="hot", origin="lower", vmin=0)
mask = axes[2].imshow(
    labels[:, :, z].T, origin="lower",
    cmap=ListedColormap(["black", "lime", "cyan"]),
    vmin=-0.5, vmax=2.5
)

for ax, title in zip(axes, ["CT", "PET", "Ground truth"]):
    ax.set_title(title)
    ax.set_aspect(gt.header.get_zooms()[1] / gt.header.get_zooms()[0])
    ax.axis("off")

cbar = fig.colorbar(mask, ax=axes[2], ticks=[0, 1, 2], fraction=0.046)
cbar.ax.set_yticklabels(["Background", "Primary tumor", "Secondary tumor"])

fig.suptitle(f"{patient_id} — Tumor slice {z}")
plt.tight_layout()
plt.show()

import os
import shutil
import json

nnunet_raw = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_raw"
dataset_name = "Dataset501_HECKTOR"

dataset_dir = os.path.join(nnunet_raw, dataset_name)
imagesTr = os.path.join(dataset_dir, "imagesTr")
labelsTr = os.path.join(dataset_dir, "labelsTr")

os.makedirs(imagesTr, exist_ok=True)
os.makedirs(labelsTr, exist_ok=True)

for patient_dir in patient_dirs:
    patient_id = os.path.basename(patient_dir)

    gt_path = os.path.join(patient_dir, f"{patient_id}.nii.gz")
    ct_path = os.path.join(patient_dir, f"{patient_id}__CT.nii.gz")
    pet_path = os.path.join(patient_dir, f"{patient_id}__PT.nii.gz")

    assert os.path.exists(gt_path), f"Missing GT: {gt_path}"
    assert os.path.exists(ct_path), f"Missing CT: {ct_path}"
    assert os.path.exists(pet_path), f"Missing PET: {pet_path}"

    # nnU-Net channel convention
    # _0000 = CT
    # _0001 = PET
    shutil.copy2(
        ct_path,
        os.path.join(imagesTr, f"{patient_id}_0000.nii.gz")
    )

    shutil.copy2(
        pet_path,
        os.path.join(imagesTr, f"{patient_id}_0001.nii.gz")
    )

    shutil.copy2(
        gt_path,
        os.path.join(labelsTr, f"{patient_id}.nii.gz")
    )

print("Copied", len(patient_dirs), "patients.")

dataset_dir = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_raw/Dataset501_HECKTOR"

dataset_json = {
    "channel_names": {
        "0": "CT",
        "1": "PET"
    },
    "labels": {
        "background": 0,
        "primary_tumor": 1,
        "secondary_tumor": 2
    },
    "numTraining": 5,
    "file_ending": ".nii.gz"
}

with open(os.path.join(dataset_dir, "dataset.json"), "w") as f:
    json.dump(dataset_json, f, indent=4)

print(json.dumps(dataset_json, indent=4))

os.environ["nnUNet_raw"] = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_raw"
os.environ["nnUNet_preprocessed"] = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_preprocessed"
os.environ["nnUNet_results"] = "/content/drive/MyDrive/HECKTOR_2026/nnUNet_results"

!nnUNetv2_preprocess -d 501 -c 2d -np 1
!nnUNetv2_preprocess -d 501 -c 3d_lowres -np 1
!nnUNetv2_preprocess -d 501 -c 3d_fullres -np 1